apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-q8lc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-q8lc@sha256:bce9622d07ae65697e6fbea2192e2e0e44e9a60059c5cf334fd78cf24fa35edb
        name: my-nodejs
        resources: {}
status: {}
